# Generated by Django 3.0.4 on 2020-07-11 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateCreated', models.DateField(auto_now_add=True)),
                ('fullName', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('phone', models.CharField(max_length=10)),
                ('projectName', models.CharField(max_length=70)),
                ('keyWord', models.CharField(max_length=70)),
                ('description', models.TextField(blank=True)),
                ('imgUrl', models.ImageField(upload_to='projects/images')),
                ('fasion', models.BooleanField(default=False)),
                ('art', models.BooleanField(default=False)),
                ('chemical', models.BooleanField(default=False)),
                ('jewellery', models.BooleanField(default=False)),
                ('graphic', models.BooleanField(default=False)),
                ('electronic', models.BooleanField(default=False)),
                ('software', models.BooleanField(default=False)),
                ('industrial', models.BooleanField(default=False)),
                ('Textil', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
