# Generated by Django 3.0.4 on 2020-07-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200711_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imgUrl',
            field=models.ImageField(upload_to='media/projects/images'),
        ),
    ]
