# Generated by Django 3.0.4 on 2020-07-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20200711_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='imgUrl',
            field=models.FileField(upload_to='proj'),
        ),
    ]
